#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-coverage
Version  : 7.0.2
Release  : 136
URL      : https://files.pythonhosted.org/packages/30/fe/88a94d564b65b2a0e224feb133941cab82d86d5833f3e7f4240d6e100b09/coverage-7.0.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/30/fe/88a94d564b65b2a0e224feb133941cab82d86d5833f3e7f4240d6e100b09/coverage-7.0.2.tar.gz
Summary  : Code coverage measurement for Python
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: pypi-coverage-bin = %{version}-%{release}
Requires: pypi-coverage-filemap = %{version}-%{release}
Requires: pypi-coverage-lib = %{version}-%{release}
Requires: pypi-coverage-license = %{version}-%{release}
Requires: pypi-coverage-python = %{version}-%{release}
Requires: pypi-coverage-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
.. Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
.. For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt

%package bin
Summary: bin components for the pypi-coverage package.
Group: Binaries
Requires: pypi-coverage-license = %{version}-%{release}
Requires: pypi-coverage-filemap = %{version}-%{release}

%description bin
bin components for the pypi-coverage package.


%package filemap
Summary: filemap components for the pypi-coverage package.
Group: Default

%description filemap
filemap components for the pypi-coverage package.


%package lib
Summary: lib components for the pypi-coverage package.
Group: Libraries
Requires: pypi-coverage-license = %{version}-%{release}
Requires: pypi-coverage-filemap = %{version}-%{release}

%description lib
lib components for the pypi-coverage package.


%package license
Summary: license components for the pypi-coverage package.
Group: Default

%description license
license components for the pypi-coverage package.


%package python
Summary: python components for the pypi-coverage package.
Group: Default
Requires: pypi-coverage-python3 = %{version}-%{release}

%description python
python components for the pypi-coverage package.


%package python3
Summary: python3 components for the pypi-coverage package.
Group: Default
Requires: pypi-coverage-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(coverage)

%description python3
python3 components for the pypi-coverage package.


%prep
%setup -q -n coverage-7.0.2
cd %{_builddir}/coverage-7.0.2
pushd ..
cp -a coverage-7.0.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672760443
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-coverage
cp %{_builddir}/coverage-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-coverage/598f87f072f66e2269dd6919292b2934dbb20492 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/coverage
/usr/bin/coverage-3.11
/usr/bin/coverage3

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-coverage

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-coverage/598f87f072f66e2269dd6919292b2934dbb20492

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
